theme: jekyll-theme-cayman
title: Programming for Fun
description: Tips for Functional and Logic Programming
permalink: /blog/:year/:month/:day/:title
github:
  is_project_page: true
  repository_url: https://github.com/NaohiroTamura
